version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    ports:
      - "3000:3000"
      - "40000:40000" # Remote Debug
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./:/goProject
